In [3]:
import numpy as np

In [4]:
arr =np.arange(0,10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [7]:
arr /100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

In [8]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [9]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
1/arr 
# 0이 존재하기 때문에 불가능하나, numpy에서는 결과가 나옴.
# 대신 0으로 나뉜 항목이 있다는 경고 표시
# 해당 항목의 자리에 무한대를 의미하는 inf 삽입.

C:\Users\adusg\.conda\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [13]:
arr/arr 
# 0을 0으로 나누었을 때 표시되는 기호 nan 삽입.
# 결론: 0이 아닌값을 0으로 나누면 inf, 0을 0으로 나누면 nan
# 그러나 이는 경고일 뿐 오류가 뜨지는 않는다.

C:\Users\adusg\.conda\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
np.log(arr)

C:\Users\adusg\.conda\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [17]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [18]:
arr.sum()

45

In [19]:
arr.mean()

4.5

In [20]:
arr.max()

9

In [21]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [22]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr_2d.shape

(3, 4)

In [24]:
arr_2d.sum()

78

In [25]:
# give me the sum, across the rows 
arr_2d.sum(axis=0)
# 각 열의 총합, 모든 열의 총합.. 행에 걸쳐서 연산 수행되기 때문

array([15, 18, 21, 24])

In [26]:
arr_2d.sum(axis=1)
#각 행의 총합. 열에 걸쳐서 연산 수행

array([10, 26, 42])