In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# indexing
arr[8]

8

In [5]:
# 범위 내의 값 가져오려는 경우 arr[start:stop(not including)]
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
# numpy는 일반적인 파이썬과 다르게.. 함수와 연산을 브로드캐스트할 수 있다.
# 예를 들면, 배열을 가져와서 이 배열의 모든 숫자에 덧셈하기.
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [11]:
# 슬라이싱은 계속해서 원래의 배열을 가리킨다?
# 무슨 의미일까?

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#배열의 슬라이스 가져오기
slice_of_arr=arr[0:6]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:]=99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr #으아아아악~~!!!

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
#원래 배열이 영향을 받지 않도록 하려면, 복사본을 만들 때 명시해야 함.
arr_copy = arr.copy()

In [20]:
slice_of_arr2=arr_copy[0:6] 

In [21]:
slice_of_arr2

array([99, 99, 99, 99, 99, 99])

In [25]:
slice_of_arr2[:]=1

In [26]:
slice_of_arr2

array([1, 1, 1, 1, 1, 1])

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
# Indexing on 2d array

In [31]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d.shape

(3, 3)

In [35]:
arr_2d[1]

array([20, 25, 30])

In [36]:
arr_2d[1][2]

30

In [37]:
arr_2d[1,2]

30

In [38]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [40]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr = np.arange(1,11)

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr > 4 #배열 내 요소가 4보다 큰 지점이 어디인지 확인 가능함 -> boolean

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
bool_arr = arr >4

In [45]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
arr[bool_arr] #true인 것만 출력됨.

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr[arr >4] #추가적인 단계 거치지 않고 바로 출력 가능

array([ 5,  6,  7,  8,  9, 10])

In [53]:
arr[arr ==2] #배열의 요소가 2와 같은 위치 찾기

array([2])

In [54]:
arr[arr <=6]

array([1, 2, 3, 4, 5, 6])