In [6]:
import numpy as np

In [7]:
mylist =[1,2,3]

In [16]:
type(mylist) # 유형: 리스트

list

In [17]:
np.array(mylist) # 유형을 리스트에서 배열로 바꾸기

array([1, 2, 3])

In [18]:
type(mylist)

list

In [21]:
arr = np.array(mylist)

In [22]:
arr

array([1, 2, 3])

In [ ]:
# 파이썬의 단일 리스트를 numpy 배열로 변환하는 것 보다 더 유용한건. ... . . 이거다.
# 중첩 리스트를 → 행렬. 즉, numpy 배열로 변환하는 것.

In [25]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [27]:
mymatrix= np.array(mylist) #2차 행렬.

In [29]:
mymatrix.shape #주피터는. .찍고 탭누르면 메소드/속성 확인가능

(3, 3)

In [36]:
np.arange(0,10) #start index, stop index. stopindex는 포함되지 않는 것.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(0,10,2) #start index, stop index, step size. 이 역시 stopindex는 포함되지 않음.

array([0, 2, 4, 6, 8])

In [40]:
np.zeros(5) #0 뒤에 붙은 점은 부동소수점을 의미. np가 부동소수점 반환하는건 나중에 더 하겠음.

array([0., 0., 0., 0., 0.])

In [41]:
type(0.0)

float

In [42]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
np.ones((5,5)) #numpy를 통해 배열에서 모든 단일 숫자로 연산할 수 있다는 장점. 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.ones((5,5)) +4 #모든 항목에 자동으로 4가 더해진다. 평범한 파이썬 리스트에서는 불가능하기에 numpy 사용.

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [48]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [49]:
[1,1,1,1] *100 #연산이 수행되는 것이 아니라, 리스트 100개가 생김

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [51]:
[1,1,1,1] + 1 #리스트에 정수를 연결할 수 없다는 오류. 두 데이터의 유형이 다르기 때문임.

TypeError: can only concatenate list (not "int") to list

In [52]:
np.ones(4) / 100 #넘파이는 이런것도 됨

array([0.01, 0.01, 0.01, 0.01])

In [54]:
np.linspace(0,10,3) #start,stop, start와 stop 사이 원하는 숫자의 개수

array([ 0.,  5., 10.])

In [55]:
np.linspace(0,10,20) #0과 10 사이에 20개의 실수. ~> lunspace: 일정한 간격으로 숫자 반환

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [56]:
len(np.linspace(0,10,20))

20

In [57]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [58]:
np.eye(5) #np.eye: 단위행렬 생성. -> 대각선에 숫자 있고 나머지는 0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
np.random.rand(1) # 0과 1 사이의 난수 1개

array([0.58495758])

In [65]:
np.random.rand(5,5) # ~균등분포.

array([[0.26208734, 0.16002082, 0.74552355, 0.92329702, 0.83728298],
       [0.14799255, 0.90421865, 0.72867586, 0.2465025 , 0.57112375],
       [0.33017936, 0.0446009 , 0.85275498, 0.81534254, 0.10167195],
       [0.85174993, 0.75884205, 0.84028151, 0.79959726, 0.61405572],
       [0.99071802, 0.20363344, 0.4932042 , 0.88458062, 0.89359429]])

In [68]:
#정규분포
#randn: 표준 정규 분포에서 하나이상의 샘플 반환.
#표준 정규 분포의 평균 = 0, 표준 편차 = 1

np.random.randn(1) #표준 정규 분포에서 1개의 숫자 반환하게 함.

array([0.63061881])

In [69]:
np.random.randn(10)

array([-0.98706325, -1.41389139,  0.49985475, -0.3645003 ,  0.60253059,
       -0.015943  ,  0.20742944, -0.37395524,  0.68121366,  1.17484799])

In [ ]:
#np.random.normal

In [70]:
np.random.randint(1,100) 
# 최솟값 포함, 최댓값 제외한 범위에서 임의 정수 반환.
# 최소,최대,[개수(옵션임)]

18

In [71]:
np.random.randint(1,100,10)

array([57, 54, 98,  6,  4, 23,  7,  9,  2, 66])

In [76]:
# 의사 난수는 ㄹㅇ 랜덤이 아니라 seed 시드를 이용해서 정해진 알고리즘에 따라.. 
# 난수처럼 보이는 수열을 만드는 것. 이 seed는 시간 등을 이용해서 자동으로 정하기도 하나,
# 우리가 직접 정할 수도 있음.
# 그러나 같은 난수가 반환되기 위해서는 시드와 난수 생성기가 같은 셀에 존재해야 함.
np.random.seed(86)
np.random.rand(4)

array([0.20260695, 0.2070931 , 0.15263774, 0.75459281])

In [77]:
np.random.seed(86)
np.random.rand(4)

array([0.20260695, 0.2070931 , 0.15263774, 0.75459281])

In [78]:
arr=np.arange(25)

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [81]:
ranarr=np.random.randint(0,50,10)

In [82]:
ranarr

array([41, 12, 30, 45, 17, 13, 41, 44, 29, 14])

In [83]:
arr.shape

(25,)

In [85]:
arr.reshape(5,5) #배열의 형태 바꾸기. 5행 5열로 표현.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(5,3) #불가능. 변경하려는 형태에 모든 요소가 들어갈 수 없기에

In [86]:
ranarr.max()

45

In [87]:
ranarr.min()

12

In [88]:
ranarr.argmin()

1

In [89]:
ranarr.argmax()

3

In [90]:
ranarr

array([41, 12, 30, 45, 17, 13, 41, 44, 29, 14])

In [91]:
# 배열에 존재하는 데이터의 유형 알아보기
ranarr.dtype

dtype('int32')